apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curriculi-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curriculi-nginx
    spec:
      containers:
      - name: curriculi-nginx
        image: %REGISTRY%/%APP_NAME%:%VERSION%
        ports:
      tolerations:
      - operator: "Exists"


