apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    name: nginx-lb
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: curriculi-nginx
#  clusterIP: 8000
